image: gitpod/workspace-full
tasks:
  - init: ./gradlew docs

vscode:
  extensions:
    - joaompinto.asciidoctor-vscode@2.7.15:4tNGcX3SbL1XiyCGQunmvQ==
    - EditorConfig.EditorConfig@0.14.5:DTIJHHNrM36zsvYRBOY3ow==
